spring:
  h2:
    console.enabled: true
    console:
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/forumlydb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: "forumly"